# These are supported funding model platforms

github: pualien
ko_fi: pualien
issuehunt: pualien
custom:['https://www.paypal.com/donate?token=C0lBLMeKNjaDwkjOyMjOlWkLlVhqjbJUBwZK7dn_xkXODIR8XoOhOcEUd_AMSacKmMtcjkieaPjoX3xi']
